// src/routes/(default)/about/principles/+page.svelte
<script>
	import Metadata from '$components/metadata.svelte';
</script>

<Metadata title="Prinsipper" />

<div class="container">
	<div class="section">
		<h1>Kompetanse og teknologi, kombinert med et brukervennlig design, er viktig for å lykkes</h1>
		<p>
			Helt siden vi startet i 2009 har vi lært av hvordan man lykkes med produkter og tjenester. Vi
			er, som mange andre i bransjen, opptatt av
			<a href="https://agilemanifesto.org/iso/no/manifesto.html"> det smidige manifestet </a>, og
			det er nok prinsippene rundt samarbeid som står oss nærest.
		</p>
		<p>
			Vi jobber best under forutsetninger hvor det lages minst og flest mulig prosjekter, som skaper
			verdi. Det handler om å bevise vår verdi, og ha insentiver som skaper et godt samarbeid og
			driver frem det beste i oss.
		</p>
		<a href="https://agilemanifesto.org/iso/no/manifesto.html">Les det smidige manifestetet</a>
	</div>
	<div class="section">
		<h2>Åpen kildekode</h2>
		<p>
			Ved å dele erfaringer, diskutere og arbeide åpent mener vi at teknologi blir bedre. Derfor
			ligger Bjerk på listen over verdens største selskaper på åpen kildekode. For deg som kunde
			betyr det at du indirekte bidrar til å skape et bedre samfunn, men også betydelig bedre
			programvare.
		</p>
		<a href="https://github.com/bjerkio">Sjekk vår Github-profil</a>
	</div>
	<div class="section">
		<h2>Lære og justere kontinuerlig</h2>
		<p>
			En viktig del av reisen er å gjøre feil, lære, reflektere og justere. For å kunne forbedre og
			forenkle hvordan mennesker tenker, jobber, lærer og kommuniserer, må vi akseptere at veien er
			ikke gått opp før vi begynner. Den blir til mens vi går.
		</p>
	</div>
	<div class="highlight">Fokuset ligger i å lære, tilpasse, navigere bedre og prøve igjen.</div>
	<div class="section">
		<h2>Åpen og gjennomsiktig prosess</h2>
		<p>
			Vi mener det er helt essensielt at vi samarbeider, og at ting skjer i det åpne. I praksis
			betyr det at vi inviterer gjerne våre kunder inn der vi jobber; (eksempelvis, Slack og
			Github).
		</p>
		<p>
			Det skal være synlig når noe skjer, bedre blir beslutningene når de taes løpende og med mest
			mulig kontekst.
		</p>
		<p>La oss unngå barriærer, og all den frustrasjonen som kommer med de.</p>
	</div>
</div>

<style>
	.container,
	.section {
		display: flex;
		flex-direction: column;
		justify-content: center;
		gap: var(--size-lg);
	}

	.container {
		max-width: 60ch;
	}

	.section {
		gap: var(--size-md);
	}

	.highlight {
		font-size: var(--font-size-lg);
		font-weight: 600;
	}
</style>

// src/pages/principles.tsx
import { Grid, Heading, Link, Paragraph } from 'theme-ui';
import { ContainerWithBackground } from '../components/container-with-background';
import { Layout } from '../components/layout/layout';

const Principles: React.FC = () => {
  return (
    <Layout>
      <Grid sx={{ width: '100%' }}>
        <ContainerWithBackground element='element5' paddingtop='190px' positionx='right' positiony='50'>
          <Grid sx={{ width: '100%' }}>
            <Paragraph variant="titlenobold">
              Kompetanse og teknologi, kombinert med et brukervennlig design, er
              viktig for å lykkes
            </Paragraph>
            <Paragraph variant="standard">
              Helt siden vi startet i 2009 har vi lært av hvordan man lykkes med
              produkter og tjenester. Vi er, som mange andre i bransjen, opptatt
              av{' '}
              <Link
                href={'https://agilemanifesto.org/iso/no/manifesto.html'}
                target={'_blank'}
                color="black"
                sx={{ textDecoration: 'underline' }}
              >
                det smidige manifestet
              </Link>
              , og det er nok prinsippene rundt samarbeid som står oss nærest.
            </Paragraph>

            <Paragraph variant="standard">
              Vi jobber best under forutsetninger hvor det lages minst og flest
              mulig prosjekter, som skaper verdi. Det handler om å bevise vår
              verdi, og ha insentiver som skaper et godt samarbeid og driver
              frem det beste i oss.
            </Paragraph>

            <Link
              href={'https://agilemanifesto.org/iso/no/manifesto.html'}
              target={'_blank'}
              sx={{ fontSize: 4 }}
            >
              Les det smidige manifestetet
            </Link>

            <Paragraph variant="subtitleblack" mt="100px">
              Åpen kildekode
            </Paragraph>
            <Paragraph variant="standard">
              Ved å dele erfaringer, diskutere og arbeide åpent mener vi at
              teknologi blir bedre. Derfor ligger Bjerk på listen over verdens
              største selskaper på åpen kildekode. For deg som kunde betyr det
              at du indirekte bidrar til å skape et bedre samfunn, men også
              betydelig bedre programvare.
            </Paragraph>
            <Link
              href={'https://github.com/bjerkio'}
              target={'_blank'}
              sx={{ fontSize: 4 }}
            >
              Sjekk vår Github-profil
            </Link>
          </Grid>
          </ContainerWithBackground>
          <ContainerWithBackground element='element4' positionx='left' positiony='40' paddingbottom='210px'>
          <Grid sx={{ gap: 3, mt: '100px' }}>
            <Heading variant="subtitleblack">
              Lære og justere kontinuerlig
            </Heading>
            <Paragraph variant="standard">
              En viktig del av reisen er å gjøre feil, lære, reflektere og
              justere. For å kunne forbedre og forenkle hvordan mennesker
              tenker, jobber, lærer og kommuniserer, må vi akseptere at veien er
              ikke gått opp før vi begynner. Den blir til mens vi går.
            </Paragraph>

            <Paragraph variant="titlenobold" mt="100px">
              Fokuset ligger i å lære, tilpasse, navigere bedre og prøve igjen.{' '}
            </Paragraph>
              

          </Grid>

          <Grid sx={{ gap: 3, mt: '100px' }}>
            <Heading variant="subtitleblack">
              Åpen og gjennomsiktig prosess
            </Heading>
            <Paragraph variant="standard">
              Vi mener det er helt essensielt at vi samarbeider, og at ting
              skjer i det åpne. I praksis betyr det at vi inviterer gjerne våre
              kunder inn der vi jobber; (eksempelvis, Slack og Github).
            </Paragraph>
            <Paragraph variant="standard">
              Det skal være synlig når noe skjer, bedre blir beslutningene når
              de taes løpende og med mest mulig kontekst.
            </Paragraph>
            <Paragraph variant="standard">
              La oss unngå barriærer, og all den frustrasjonen som kommer med
              de.{' '}
            </Paragraph>
          </Grid>
          </ContainerWithBackground>
      </Grid>
    </Layout>
  );
};

export default Principles;
