// components/layout/footer/footer.tsx
import { Box, Container, Flex, Link, Text } from '@chakra-ui/react';

export const Footer: React.FC = () => (
  <Box sx={{ minHeight: '5vh', background: 'dark100', mt: 'auto', p: '30px' }}>
    <Container variant="full">
      <Flex
        sx={{
          color: 'background',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: 'base',
        }}
      >
        <Flex>
          <Text color="green20">
            Kontakt oss på{' '}
            <Link href={'mailto:kontoret@bjerk.io'} variant={{base:"footerLink"}}>
              kontoret@bjerk.io
            </Link>
          </Text>
        </Flex>
        <Flex sx={{ color: 'green20' }}>© Bjerk 2022</Flex>
      </Flex>
    </Container>
  </Box>
);

// src/components/footer.svelte
<div class="outer-container">
	<footer class="container">
		<p>
			<b>Bjerk AS</b><br />
			Organisasjonsnummer: 930 334 693<br />
		</p>
		<p class="highlight">
			Kontakt oss på <a href="mailto:kontoret@bjerk.io">kontoret@bjerk.io</a>
		</p>
	</footer>
</div>

<style>
	.outer-container {
		background-color: var(--foreground-color);
		color: var(--text-color-light);
	}

	a {
		color: var(--text-color-light);
	}

	.container {
		padding-top: var(--size-lg);
		padding-bottom: var(--size-lg);

		display: flex;
		flex-direction: column;
		justify-content: center;
		gap: var(--size-md);
	}

	.highlight {
		font-size: var(--font-size-base);
	}
</style>
