// src/components/layouts/components/header/header.tsx
import React, { useState } from "react";
import { Box, Container, Flex } from "theme-ui";
import { Link } from "next-theme-ui";
import { Text } from "../../../text";
import { Logo } from "../logo";
import Hamburger from "./hamburger";

const Header: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  // TODO: implement mobile navbar
  return (
    <React.Fragment>
      <Container variant="centered" sx={{ my: 4 }}>
        <Flex
          sx={{
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <Link href="/" aria-label="Bjerk Logo">
            <Logo
              color="black"
              dotColor="primary"
              sx={{
                alignItems: "flex-start",
                color: "black",
                width: "5em",
              }}
            />
          </Link>

          <Box
            sx={{
              display: ["block", "none"],
              position: ["fixed", "static"],
              top: 0,
              right: 0,
              zIndex: 1001,
            }}
          >
            <Hamburger isOpen={isOpen} onClick={setIsOpen} />
          </Box>

          <Box
            sx={{ display: ["none", "block"] }}
            onClick={() => setIsOpen(false)}
          >
            <Flex as="nav" variant="nav">
              <Link href="/services">
                <Text id="nav-services" defaultMessage="Services" />
              </Link>
              <Link href="/about">
                <Text id="nav-about" defaultMessage="About" />
              </Link>
              <Link href="/contact">
                <Text id="nav-contact" defaultMessage="Contact" />
              </Link>
            </Flex>
          </Box>

          {isOpen && (
            <Box
              sx={{
                display: ["block", "none"],
                position: "fixed",
                top: 0,
                left: 0,
                zIndex: 10,
              }}
            ></Box>
          )}
        </Flex>
      </Container>
    </React.Fragment>
  );
};

export default Header;

// src/components/header.svelte
<header>
	<a class="logo" href="/">
		<img src="/assets/logo.svg" alt="Bjerk logo" />
	</a>
	<nav>
		<ul>
			<li><a href="/about">About us</a></li>
			<li><a href="/contact">Contact</a></li>
		</ul>
	</nav>
</header>

<style lang="scss">
	header {
		display: flex;
		justify-content: space-between;
		align-items: center;

		.logo {
			img {
				width: 100%;
			}
			color: var(--text-color);
			display: inline-block;
		}
	}

	nav {
		ul {
			display: flex;
			list-style: none;

			li {
				margin-left: 1rem;

				a {
					color: var(--text-color);
					text-decoration: none;

					&:hover {
						font-weight: 500;
					}
				}

				&:first-child {
					margin-left: 0;
				}
			}
		}
	}
</style>
